const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const vm = require('node:vm');
const context = { document: { body: {}, documentElement: {} } };
vm.createContext(context);
vm.runInContext(readFileSync('static/app.js', 'utf8'), context);
(async () => {
  const app = context.app();
  const now = new Date();
  assert.equal(app.historyMonth, now.getFullYear() + '-' + String(now.getMonth() + 1).padStart(2, '0'));
  let scrolled = 0;
  app.$nextTick = fn => fn();
  app.$refs = { historyResults: { scrollIntoView() { scrolled++; }, focus() {} } };
  app.showToast = () => {};
  app.clients = [{ id: 'a', name: 'Willow House' }, { id: 'b', name: 'Other client' }];
  app.entries = Array.from({ length: 23 }, (_, i) => ({ id: 'recent-' + i, date: '2026-01-15', client_id: 'a', amount: 10 }));
  app.entries.push({ id: 'old', date: '2018-06-10', client_id: 'a', amount: 25 });
  app.entries.push({ id: 'other', date: '2026-02-10', client_id: 'b', amount: 30 });
  app.expenses = [{ id: 'supplies', date: '2020-03-04', client_id: 'a', amount: 3.49, description: 'Cloths' }];
  app.setHistoryMonth('2026-01');
  assert.equal(app.filteredHistory.length, 23);
  assert.equal(app.historyTotal, 230);
  assert.equal(app.historyPageCount, 3);
  const firstPage = app.visibleHistory.map(e => e.id);
  app.changeHistoryPage(1);
  assert.equal(app.visibleHistory.length, 10);
  assert.ok(app.visibleHistory.every(e => !firstPage.includes(e.id)));
  assert.equal(app.historyResultLabel, '11–20 of 23 records');
  app.changeHistoryPage(1);
  assert.equal(app.visibleHistory.length, 3);
  app.changeHistoryPage(1);
  assert.equal(app.currentHistoryPage, 3);
  assert.equal(scrolled, 3);

  app.setHistoryMonth('2026-01');
  app.shiftHistoryMonth(-1);
  assert.equal(app.historyMonth, '2025-12');
  app.shiftHistoryMonth(1);
  assert.equal(app.historyMonth, '2026-01');
  for (const invalid of ['', 'bad', '2026-13', '0000-01']) app.setHistoryMonth(invalid);
  assert.equal(app.historyMonth, '2026-01');
  app.setHistoryMonth('0001-01'); app.shiftHistoryMonth(-1);
  assert.equal(app.historyMonth, '0001-01');
  app.setHistoryMonth('9999-12'); app.shiftHistoryMonth(1);
  assert.equal(app.historyMonth, '9999-12');

  app.historyClientId = 'a';
  app.setHistoryMonth('2026-02');
  assert.equal(app.filteredHistory.length, 0);
  assert.equal(app.latestHistoryMonth, '2026-01');
  app.setHistoryMonth(app.latestHistoryMonth);
  assert.equal(app.visibleHistory.length, 10);
  app.historySearch = '2018';
  app.historyPage = 1;
  assert.equal(app.visibleHistory[0].id, 'old');
  assert.equal(app.historyTotal, 25);
  app.historySearch = '';
  assert.equal(app.filteredHistory.length, 23);
  app.historySearch = '   ';
  assert.equal(app.historySearching, false);
  assert.equal(app.filteredHistory.length, 23);
  app.historyMode = 'expenses';
  assert.equal(app.latestHistoryMonth, '2020-03');
  app.historySearch = 'CLOTHS';
  assert.equal(app.visibleHistory[0].id, 'supplies');

  // Editing a record keeps its page; moving it out of a filter clamps the page.
  app.historyMode = 'work'; app.historySearch = ''; app.setHistoryMonth('2026-01');
  app.entries = app.entries.slice(0, 11); app.historyPage = 2;
  app.editor = { saving: false, kind: 'work', draft: { ...app.visibleHistory[0] } };
  app.finishEditing = () => {};
  app.api = async () => ({ ...app.editor.draft, amount: 12 });
  await app.saveEdit();
  assert.equal(app.historyPage, 2);
  app.api = async () => ({ ...app.editor.draft, date: '2025-12-01' });
  await app.saveEdit();
  assert.equal(app.historyPage, 1);
  assert.equal(app.visibleHistory.length, 10);
  app.entries.push({ id: 'last', date: '2026-01-01', client_id: 'a', amount: 10 });
  app.historyPage = 2;
  app.deleteEntry('last'); app.api = async () => ({});
  await app.confirmDelete();
  assert.equal(app.historyPage, 1);

  app.lastSaved = { id: 'saved-old', date: '2015-01-01', client_id: 'a', kind: 'work', amount: 20 };
  app.entries.push(app.lastSaved);
  app.onTabSwitch = () => {};
  app.viewSaved();
  assert.equal(app.historyMonth, '2015-01');
  assert.equal(app.visibleHistory[0].id, 'saved-old');
  console.log('History month boundaries, all-year search, paging, filtered latest month, edits and deletions passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
