const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const vm = require('node:vm');
const context = { URLSearchParams, setTimeout, clearTimeout, window: {}, document: { body: {}, documentElement: {} } };
vm.createContext(context);
vm.runInContext(readFileSync('static/app.js', 'utf8'), context);

(async () => {
  const app = context.app();
  app.showToast = () => {};
  app.clients = [{ id: 'a', name: 'Long client name' }, { id: 'b', name: 'Other client' }];
  app.entries = Array.from({ length: 25 }, (_, i) => ({ id: String(i), client_id: i % 2 ? 'a' : 'b', date: '2026-01-01', amount: 15, hours: 1 }));
  app.expenses = [{ id: 'expense', client_id: 'a', date: '2026-01-02', amount: 3.49, description: 'Microfibre cloths' }];
  app.setHistoryMonth('2026-01');
  assert.equal(app.visibleHistory.length, 10);
  app.historyClientId = 'a';
  assert.equal(app.filteredHistory.length, 12);
  assert.equal(app.historyTotal, 180);
  app.historyMode = 'expenses';
  app.historySearch = 'CLOTH';
  assert.equal(app.filteredHistory.length, 1);
  app.historySearch = '3.49';
  assert.equal(app.historyTotal, 3.49);
  app.historySearch = 'missing';
  assert.equal(app.filteredHistory.length, 0);

  app.logClientId = 'a';
  app.expAmount = 3.49;
  app.expDesc = 'Cloths';
  app.api = async () => { throw new Error('Offline'); };
  await app.saveExpense();
  assert.equal(app.logError, 'Offline');
  assert.equal(app.expAmount, 3.49);
  assert.equal(app.expDesc, 'Cloths');
  let resolve, calls = 0;
  app.api = () => { calls++; return new Promise(done => { resolve = done; }); };
  const saving = app.saveExpense();
  await app.saveExpense();
  assert.equal(calls, 1);
  resolve({ id: 'new', client_id: 'a', date: '2026-01-02', amount: 3.49 });
  await saving;
  assert.equal(app.expenses.length, 2);
  assert.equal(app.lastSaved.id, 'new');
  assert.equal(app.saving, false);
  app.workEnd = app.workStart;
  await app.saveWork();
  assert.match(app.logError, /different start/);

  app.deleteExpense('expense');
  app.api = async () => { throw new Error('Offline'); };
  await app.confirmDelete();
  assert.equal(app.deleteConfirm.show, true);
  assert.equal(app.expenses.length, 2);
  assert.match(app.deleteError, /Unable to delete/);
  app.api = async () => ({});
  await app.confirmDelete();
  assert.equal(app.deleteConfirm.show, false);
  assert.equal(app.expenses.length, 1);

  app.reportMode = 'monthly';
  app.reportClientId = 'a';
  app.selectedMonth = '';
  let urls = [];
  app.api = async url => { urls.push(url); return { available_months: [{ year: 2026, month: 1 }], sessions: 1, expenses: [] }; };
  await app.loadMonthly();
  assert.equal(app.selectedMonth, '2026-1');
  assert.equal(urls.length, 2);
  assert.equal(app.canInvoice, true);
  app.api = async () => { throw new Error('Offline'); };
  await app.loadMonthly();
  assert.match(app.reportError, /Unable to load/);
  assert.equal(app.canInvoice, false);
  assert.equal(app.reportLoading, false);

  let oldDone, newDone;
  app.api = () => new Promise(done => { oldDone = done; });
  const old = app.loadMonthly();
  app.reportClientId = 'b';
  app.api = () => new Promise(done => { newDone = done; });
  const recent = app.loadMonthly();
  newDone({ available_months: [{ year: 2026, month: 1 }], sessions: 7, expenses: [] });
  await recent;
  oldDone({ available_months: [{ year: 2026, month: 1 }], sessions: 1, expenses: [] });
  await old;
  assert.equal(app.monthlyData.sessions, 7);

  app.loadRange = async () => {};
  await app.setRangePreset('lastmonth');
  const start = new Date(app.rangeStart + 'T12:00:00');
  const end = new Date(app.rangeEnd + 'T12:00:00');
  assert.equal(start.getDate(), 1);
  assert.equal(start.getMonth(), end.getMonth());
  end.setDate(end.getDate() + 1);
  assert.equal(end.getDate(), 1);
  await app.setRangePreset('week');
  assert.equal(new Date(app.rangeStart + 'T12:00:00').getDay(), 1);
  assert.ok(app.rangeStart <= app.rangeEnd);
  console.log('Mobile UX: search, pagination, save/retry, duplicate submission, deletion failure, report races and date shortcuts passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
